format = """
$username$hostname$directory$git_branch$git_status$time
$character
"""

[username]
style_user = "bold blue"
show_always = true

[hostname]
ssh_only = false
style = "bold cyan"
format = "[$hostname](bold cyan) "

[directory]
style = "bold yellow"
truncation_length = 3
truncation_symbol = "â€¦/"
read_only = " ï ½"
read_only_style = "red"

[git_branch]
symbol = "ï˜ "
style = "bold green"

[git_status]
style = "green"
format = '([$all_status$ahead_behind](green) )'

[time]
disabled = false
format = "[$time](bold magenta) "
time_format = "%T"
style = "bold magenta"

[character]
success_symbol = "[âœ](green)"
error_symbol = "[âœ](red)"


[terraform]
format = '[ğŸğŸ’¨ $version$workspace]($style) '

[dotnet]
symbol = 'ğŸ¥… '
style = 'green'
heuristic = false